@host = localhost
@port = 3000
@apiversion = api/v1

### Recover A Category By ID
GET http://{{host}}:{{port}}/{{apiversion}}/categories/06e7b01d-28d6-423f-91b4-2a21063a2a72

### Recover All Categories
GET http://{{host}}:{{port}}/{{apiversion}}/categories

### Insert A Category
POST http://{{host}}:{{port}}/{{apiversion}}/categories
Content-type: application/json

{
    "name":"Sala de Estar"
}

### Update A Category
PUT http://{{host}}:{{port}}/{{apiversion}}/categories/06e7b01d-28d6-423f-91b4-2a21063a2a72
Content-type: application/json

{
    "id":"06e7b01d-28d6-423f-91b4-2a21063a2a72",
    "name":"Betão"
}

### Delete A Category
DELETE http://{{host}}:{{port}}/{{apiversion}}/categories/5e36274c-92a3-4064-b182-35a5fe38e8e1