@host = localhost
@port = 3000
@apiversion = api/v1

### Recover A Category By ID
GET http://{{host}}:{{port}}/{{apiversion}}/categories/9939ed02-8e9b-4cb5-a8b6-821efc57abc9

### Recover All Categories
GET http://{{host}}:{{port}}/{{apiversion}}/categories

### Insert A Category
POST http://{{host}}:{{port}}/{{apiversion}}/categories
Content-type: application/json
Authorization: Bearer <token>

{
    "name":"Banho"
}

### Update A Category
PUT http://{{host}}:{{port}}/{{apiversion}}/categories/6039b800-646c-4825-8dc5-b7c5f11dc0ff
Content-type: application/json
Authorization: Bearer <token>

{
    "id": "6039b800-646c-4825-8dc5-b7c5f11dc0ff",
    "name": "Mesa"
}

### Delete A Category
DELETE http://{{host}}:{{port}}/{{apiversion}}/categories/627527c7-0e4a-4038-8eb1-b1c359afb2a8
Authorization: Bearer <token>
