@host = localhost
@port = 3000
@apiversion = api/v1

### Recover A Category By ID
GET http://{{host}}:{{port}}/{{apiversion}}/categories/ba5cf083-5387-47c0-831f-815dae315a2f

### Recover All Categories
GET http://{{host}}:{{port}}/{{apiversion}}/categories

### Insert A Category
POST http://{{host}}:{{port}}/{{apiversion}}/categories
Content-type: application/json

{
    "name":"Sala de Estar"
}

### Update A Category
PUT http://{{host}}:{{port}}/{{apiversion}}/categories/ba5cf083-5387-47c0-831f-815dae315a2f
Content-type: application/json

{
    "id":"ba5cf083-5387-47c0-831f-815dae315a2f",
    "name":"Betão"
}

### Delete A Category
DELETE http://{{host}}:{{port}}/{{apiversion}}/categories/06e7b01d-28d6-423f-91b4-2a21063a2a72


### 1e1ba042-fa93-40e9-9b74-2a1fdfcd4c60
### a22a6030-bf2f-424b-b72e-2ca49e774094
### 06e7b01d-28d6-423f-91b4-2a21063a2a72
