@host = localhost
@port = 3000
@apiversion = api/v1

### Recover Product By Id
GET http://{{host}}:{{port}}/{{apiversion}}/products/570fa8b1-5865-41bb-aaec-2f8da430774c

### Recover All Products
GET http://{{host}}:{{port}}/{{apiversion}}/products

### Insert A Product
POST http://{{host}}:{{port}}/{{apiversion}}/products
Content-type: application/json

{
    "name":"Chuveiro elétrico",
    "description": "Um ótimo chuveiro elétrico, super moderno",
    "value": 450,
    "categories": [
        {
            "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
            "name": "Banho"
        }
    ]
}

### Update A Product
PUT http://{{host}}:{{port}}/{{apiversion}}/products/570fa8b1-5865-41bb-aaec-2f8da430774c
Content-type: application/json

{
    "id": "570fa8b1-5865-41bb-aaec-2f8da430774c",
    "name": "Toalha",
    "description": "Toalha para banho",
    "value": 50,
    "categories": [
      {
        "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
        "name": "Banho"
      }
    ]
  }

### Delete A Product
DELETE http://{{host}}:{{port}}/{{apiversion}}/products/19245b61-aade-443c-9176-b740e11796f4

### Add Category Product
POST http://{{host}}:{{port}}/{{apiversion}}/products/add-category/570fa8b1-5865-41bb-aaec-2f8da430774c
Content-Type: application/json

{
  "id": "570fa8b1-5865-41bb-aaec-2f8da430774c",
  "name": "Toalha",
  "description": "Toalha para banho",
  "value": 50,
  "categories": [
    {
      "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
      "name": "Banho"
    }
  ]
}

### Remove Category Product
DELETE http://{{host}}:{{port}}/{{apiversion}}/products/remove-category/dab5bed8-1241-4611-b916-8f9ed1059451
Content-Type: application/json

{
  "id": "570fa8b1-5865-41bb-aaec-2f8da430774c",
  "name": "Toalha",
  "description": "Toalha para banho",
  "value": 50,
  "categories": [
    {
      "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
      "name": "Banho"
    }
  ]
}

### Recover Products By Category
GET http://{{host}}:{{port}}/{{apiversion}}/products/category/6039b800-646c-4825-8dc5-b7c5f11dc0ff

### Alter Status Product
PUT http://{{host}}:{{port}}/{{apiversion}}/products/status/6039b800-646c-4825-8dc5-b7c5f11dc0ff
Content-Type: application/json

{
  "id": "570fa8b1-5865-41bb-aaec-2f8da430774c",
  "name": "Toalha",
  "description": "Toalha para banho",
  "value": 50,
  "categories": [
    {
      "id": "6039b800-646c-4825-8dc5-b7c5f11dc0ff",
      "name": "Mesa"
    }
  ],
  "status": "ACTIVE"
}
