@host = localhost
@port = 3000
@apiversion = api/v1

### Recover Product By Id
GET http://{{host}}:{{port}}/{{apiversion}}/products/dab5bed8-1241-4611-b916-8f9ed1059451

### Recover All Products
GET http://{{host}}:{{port}}/{{apiversion}}/products

### Insert A Product
POST http://{{host}}:{{port}}/{{apiversion}}/products
Content-type: application/json

{
    "name":"Chuveiro elétrico",
    "description": "Um ótimo chuveiro elétrico, super moderno",
    "value": 450,
    "categories": [
        {
            "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
            "name": "Banho"
        }
    ]
}

### Update A Product
PUT http://{{host}}:{{port}}/{{apiversion}}/products/dab5bed8-1241-4611-b916-8f9ed1059451
Content-type: application/json

{
  "id": "dab5bed8-1241-4611-b916-8f9ed1059451",
  "name": "Conjunto de banheiro",
  "description": "Conjunto de peças para decorar o banheiro, peças de cores vivas",
  "value": 150,
  "categories": [
    {
      "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
      "name": "Banho"
    },
    {
      "id": "6039b800-646c-4825-8dc5-b7c5f11dc0ff",
      "name": "Mesa"
    }
  ]
}

### Delete A Product
DELETE http://{{host}}:{{port}}/{{apiversion}}/products/19245b61-aade-443c-9176-b740e11796f4

### Add Category Product
POST http://{{host}}:{{port}}/{{apiversion}}/products/add-category/dab5bed8-1241-4611-b916-8f9ed1059451
Content-Type: application/json

{
  "id": "dab5bed8-1241-4611-b916-8f9ed1059451",
  "name": "Conjunto de banheiro",
  "description": "Conjunto de peças para decorar o banheiro, peças de cores vivas",
  "value": 150,
  "categories": [
    {
      "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
      "name": "Banho"
    }
  ]
}

### Remove Category Product
DELETE http://{{host}}:{{port}}/{{apiversion}}/products/remove-category/dab5bed8-1241-4611-b916-8f9ed1059451
Content-Type: application/json

{
  "id": "dab5bed8-1241-4611-b916-8f9ed1059451",
  "name": "Conjunto de banheiro",
  "description": "Conjunto de peças para decorar o banheiro, peças de cores vivas",
  "value": 150,
  "categories": [
    {
      "id": "1aa1a296-85bf-49be-8173-17c33b70073c",
      "name": "Banho"
    },
    {
      "id": "9939ed02-8e9b-4cb5-a8b6-821efc57abc9",
      "name": "Cama"
    }
  ]
}
